[package]
name = "menoid_aptos"
version = "1.0.0"
authors = []

[addresses]
noid = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-stdlib"

[dev-dependencies]
