[package]
name = "noid"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
noid = "0x0"

[environments]
localnet = "b1060952"
testnet  = "4c78adac"
mainnet  = "35834a8a"
