const fs = require("fs");
const path = require("path");

function toBE32(valStr) {
  const val = BigInt(valStr);
  const buf = new Uint8Array(32);
  let temp = val;
  for (let i = 31; i >= 0; i--) {
    buf[i] = Number(temp & 0xffn);
    temp >>= 8n;
  }
  return Array.from(buf);
}

function parseG1(pt) {
  return [...toBE32(pt[0]), ...toBE32(pt[1])];
}

function parseG2(pt) {
  return [
    ...toBE32(pt[0][1]),
    ...toBE32(pt[0][0]),
    ...toBE32(pt[1][1]),
    ...toBE32(pt[1][0]),
  ];
}

function formatBytes(bytes) {
    return "[" + bytes.map(b => `0x${b.toString(16).padStart(2, "0")}`).join(", ") + "]";
}

function formatIC(icList) {
  const lines = icList.map(pt => `    ${formatBytes(parseG1(pt))},`);
  return "[\n" + lines.join("\n") + "\n  ]";
}

function parseKeyFile(filePath, name) {
  const raw = fs.readFileSync(filePath, "utf8");
  const vk = JSON.parse(raw);

  const alpha = parseG1(vk.vk_alpha_1);
  const beta = parseG2(vk.vk_beta_2);
  const gamma = parseG2(vk.vk_gamma_2);
  const delta = parseG2(vk.vk_delta_2);

  return `
// Verifying Key for ${name}
pub const ${name}_VK: Groth16Verifyingkey<'static> = Groth16Verifyingkey {
    nr_pubinputs: ${vk.nPublic},
    vk_alpha_g1: ${formatBytes(alpha)},
    vk_beta_g2: ${formatBytes(beta)},
    vk_gamme_g2: ${formatBytes(gamma)},
    vk_delta_g2: ${formatBytes(delta)},
    vk_ic: &${formatIC(vk.IC)},
};
`;
}

function main() {
  const aptosZkDir = path.join(__dirname, "../../aptos/zk_build");
  const depPath = path.join(aptosZkDir, "deposit_verification_key.json");
  const traPath = path.join(aptosZkDir, "transfer_verification_key.json");
  const witPath = path.join(aptosZkDir, "withdraw_verification_key.json");

  let rustContent = `// This file is auto-generated by app/parse_vk.js. Do not edit manually.
use groth16_solana::groth16::Groth16Verifyingkey;

`;

  rustContent += parseKeyFile(depPath, "DEPOSIT");
  rustContent += parseKeyFile(traPath, "TRANSFER");
  rustContent += parseKeyFile(witPath, "WITHDRAW");

  const outPath = path.join(__dirname, "../programs/noid_solana/src/verifying_keys.rs");
  fs.writeFileSync(outPath, rustContent, "utf8");
  console.log(`Successfully generated verifying_keys.rs at ${outPath}`);
}

main();
